theme-shoka-x/hexo-theme-shokaX

layout/_mixin/card.pug
source/css/_common/components/pages/home.styl

fix: 卡片显示异常

---

source/css/_common/scaffolding/base.styl

Test file
```yaml
{% pullquote left %}
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
{% endpullquote %}
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas tempus molestie arcu, et fringilla mauris placerat ac. Nullam luctus bibendum risus. Ut cursus sed ipsum feugiat egestas. Suspendisse elementum, velit eu consequat consequat, augue lorem dapibus libero, eget pulvinar dolor est sit amet nulla. Suspendisse a porta tortor, et posuere mi. Pellentesque ultricies, mi quis volutpat malesuada, erat felis vulputate nisl, ac congue ante tortor ut ante. Proin aliquam sem vel mauris tincidunt, eget scelerisque tortor euismod. Nulla tincidunt enim nec commodo dictum. Mauris id sapien et orci gravida luctus id ut dui. In vel vulputate odio. Duis vel turpis molestie, …
```

feat: support pullquote

---

source/css/_common/outline/header/image.styl
source/css/_common/outline/header/waves.styl

perf: 优化头图显示

---

source/js/_app/global.js
source/js/_app/global.ts

貌似可以解决 #47 中的问题，但不能保证会不会有什么副作用
建议再测测（）

fix: 尝试修复sidebar抽动

---

source/css/_common/components/highlight/highlight.styl
source/css/_common/outline/header/image.styl
source/css/_common/outline/header/waves.styl
source/css/_common/scaffolding/animate.styl
source/js/_app/global.ts
source/js/_app/page.ts

perf: 视口外时停止动画

---

layout/_partials/footer.pug

refactor: 处理迁移剩余工作

---

.github/workflows/build-theme.yml

在Build后添加了一个Test步骤，保证Main分支可以正常生成

ci: 添加Test

---

_config.yml
source/js/_app/fireworks.ts
source/js/_app/library.ts
source/js/_app/page.ts
source/js/_app/vue.ts

refactor: 引入theme-shokax-anime

---

docs/guide/performance.md
languages/en.yml
languages/zh-HK.yml
languages/zh-TW.yml

#75 的部分实现
基于zh-CN重新翻译了繁体中文和英文
补充了缺少的本地化键

refactor: 基于zh-CN重新翻译语言文件

---

layout/_mixin/comment.pug

目前評論區感覺太靠邊了，看了一下是css class名稱打錯了

fix: 修正評論區間距問題

---

_config.yml
layout/_partials/post/footer.pug

調整pageview區塊為僅有twikoo開啟或者waline的pageview開啟時才會顯示

fix: 微調pageview顯示

---

layout/_mixin/widgets.pug
scripts/helpers/asset.ts

fix: 修正waline最新評論樣式

---

layout/_mixin/comment.pug

fix: waline暗黑模式

---

source/js/_app/components.ts
source/js/_app/fireworks.ts
source/js/_app/global.ts
source/js/_app/library.ts
source/js/_app/page.ts
source/js/_app/player.ts
source/js/_app/vue.ts

perf: change to modern javascript

---

layout/_mixin/widgets.pug
scripts/helpers/asset.ts

fix: 最新评论跳转

---

scripts/generaters/script.ts

fix: firework color

---

scripts/generaters/index.ts

fix: Index 在有且只有置顶文章时渲染错误

---

scripts/generaters/index.ts

fix: Index 无法正确渲染 sticky 显式设置为 false 的文章

---

layout/_mixin/comment.pug
layout/_partials/head/head.pug
scripts/helpers/asset.ts

waline的css、mjs国内加载缓慢，使用jsdelivr加速

使用jsdelivr加速waline在国内访问速度

---

scripts/helpers/asset.ts

fix: 解决最新评论 // 显示错误

---

_config.yml
source/css/_common/scaffolding/base.styl
source/css/_iconfont.styl

fix: 更新iconfont链接

---

README.md
README_en.MD

- 添加英文文档中的英文文档链接
- 添加技术栈介绍
- 修改一些链接 `http` => `https`

优化英文文档和部分中文文档

---

source/css/_common/components/third-party/third-party.styl

Reverts theme-shoka-x/hexo-theme-shokaX#207
上游已修复

Revert "fix: waline溢出"

---

.github/dependabot.yml
.github/workflows/build-theme.yml
.github/workflows/codeql-analysis.yml
.github/workflows/npm-publish.yml
scripts/generaters/script.ts
source/js/_app/components/sidebar.ts
source/js/_app/globals/handles.ts
source/js/_app/globals/themeColor.ts
source/js/_app/globals/thirdparty.ts
source/js/_app/library/declare.d.ts
source/js/_app/library/proto.ts
source/js/_app/page/fancybox.ts
source/js/_app/page/post.ts
source/js/_app/page/tab.ts
source/js/_app/pjax/domInit.ts
source/js/_app/pjax/refresh.ts
source/js/_app/player.ts

refactor/ci: 移除 attr 函数 & 更新工作流 & 使用 esbuild 静态常量优化编译

---

languages/README.md
languages/ar.yml
languages/de.yml
languages/es.yml
languages/fr.yml
languages/hi.yml
languages/id.yml
languages/it.yml
languages/ko.yml
languages/nl.yml
languages/pl.yml
languages/pt.yml
languages/ru.yml
languages/tr.yml
languages/vi.yml

- Provides high-quality, locally spoken translations into 14 languages. | 提供优质，本地口语化的14个语言翻译。
- ### English (en)
- ### 日本語 (ja)
- ### 中文-简体 (zh-CN)
- ### 中文-繁体 (zh-HK)
- ### 中文-台湾 (zh-TW)
- ### Español (es) - 西班牙語
- ### Deutsch (de) - 德語
- ### Français (fr) - 法語
- ### Italiano (it) - 意大利语
- ### Português (pt) - 葡萄牙语
- ### Русский (ru) - 俄语
- ### العربية (ar) - 阿拉伯语
- ### हिंदी (hi) - 印地语
- ### 한국어 (ko) - 韩语
- ### Nederlands (nl) - 荷兰语
- ### Polski (pl) - 波兰语
- ### Türkçe (tr) - 土耳其语
- ### Bahasa Indonesia (id) - 印度尼西亚语
- ### Tiếng Việt (vi) - 越南语

Update: Added 14 new language packs

---

scripts/helpers/asset.ts

feat: remove 300 weight font

---

layout/_partials/footer.pug
layout/_partials/head/head_com.pug
layout/_partials/layout.pug
layout/_partials/sidebar/menu.pug
source/css/_common/outline/footer/footer.styl

perf: lighthouse

---

layout/_partials/post/footer.pug
package.json

fix: fit new pageview

---

layout/_partials/layout.pug

https://github.com/polyfillpolyfill/polyfill-service/issues/2873
polyfill.io 已经不再安全

fix: 移除polyfill.io

---

source/js/_app/components/sidebar.ts

具体错误可以参考:https://github.com/next-theme/hexo-theme-next/issues/19
改动参考了:https://github.com/next-theme/hexo-theme-next/commit/b0d92b7b6cf632753c4fcca2512e01cf006428df

fix:修复标题首字符为数字时无法加载的错误

---

_config.yml
layout/_partials/layout.pug
layout/_partials/post/nav.pug

新增三个选项
- 是否开启首页头图
- 是否预加载头图
- 是否把CSS渐变作为上/下一页封面

feat: 实验特性,添加coverConfig来配置头图

---

_config.yml
scripts/generaters/script.ts
source/js/_app/library/declare.d.ts
source/js/_app/page/post.ts

feat: 支持复制时小于自定义字数的时候不添加版权信息

---

source/css/_common/outline/sidebar/quick.styl

fix: 修复iPadOS横屏模式下quick功能栏错位
